//
//   Code generated by ChatGPT for the query below
//
//   Can you write me OpenSCAD code to create a model of a frying pan?
//
//   Created Jan 2023 by Jenny List, for a Hackaday article.
//


module frying_pan() {
  difference() {
    union() {
      cylinder(r=30, h=10, center=true);
      translate([0, 0, 10]) cylinder(r=35, h=5, center=true);
    }
    cylinder(r=38, h=12, center=true);
  }
}

frying_pan();
