//
//   Code generated by ChatGPT for the query below
//
//   Can you write me OpenSCAD code to create a model of a mug?
//
//   Created Jan 2023 by Jenny List, for a Hackaday article.
//


module mug() {
  difference() {
    union() {
      cylinder(r=30, h=60, center=true);
      translate([0, 0, 60]) cylinder(r=25, h=20, center=true);
    }
    cylinder(r=28, h=62, center=true);
  }
}

mug();