//
//   Code generated by ChatGPT for the query below
//
//   Can you write me OpenSCAD code to create a model of a spatula?
//
//   Created Jan 2023 by Jenny List, for a Hackaday article.
//


module spatula() {
  union() {
    cylinder(r=10, h=30, center=true);
    translate([0, 0, -15]) cylinder(r=5, h=20, center=true);
    translate([0, 0, -30]) cube([20, 5, 5], center=true);
  }
}

spatula();