//
//   Code generated by ChatGPT for the query below
//
//   Can you write me OpenSCAD code to create a model of a teaspoon?
//
//   Created Jan 2023 by Jenny List, for a Hackaday article.
//


module teaspoon() {
  union() {
    cylinder(r=5, h=15, center=true);
    translate([0, 0, -7.5]) cylinder(r=3, h=15, center=true);
    translate([0, 0, -15]) cylinder(r=2, h=15, center=true);
  }
}

teaspoon();